deploy:
  stage: deploy
  variables:
    HEROKU_APP: alexaisasexybo
    HEROKU_TOKEN: 7e64da3c-4174-4dd6-92a0-a35a7762dba3
  only:
    - master
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_TOKEN