deploy:
  stage: deploy
  variables:
    HEROKU_APP: alexaisasexybot
    HEROKU_TOKEN: 8202228a-6ee9-4b23-bd72-1ef0922119be
  only:
    - master
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_TOKEN